/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ul;

import javax.swing.JLabel;
import javax.swing.JPanel;
import com.utils.Hover;
import com.utils.TabbedPane;

/**
 *
 * @author korea
 */
public class ThongKePanel extends javax.swing.JPanel {

    /**
     * Creates new form ThongKePanel
     */
    public ThongKePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnHoaDon = new javax.swing.JLabel();
        btnDoanhThu = new javax.swing.JLabel();
        btnSanPham = new javax.swing.JLabel();
        pnlCards = new javax.swing.JPanel();
        pnlDoanhThu = new com.ul.DoanhThuPanel();
        pnlHoaDon = new com.ul.TKHoaDonPanel();
        pnlSanPham = new com.ul.TKSanPhamPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));

        btnHoaDon.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHoaDon.setText("HÓA ĐƠN");
        btnHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHoaDonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHoaDonMouseExited(evt);
            }
        });

        btnDoanhThu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnDoanhThu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDoanhThu.setText("DOANH THU");
        btnDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDoanhThuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDoanhThuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDoanhThuMouseExited(evt);
            }
        });

        btnSanPham.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSanPham.setText("SẢN PHẨM");
        btnSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSanPhamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSanPhamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSanPhamMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(btnDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 368, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pnlCards.setBackground(new java.awt.Color(255, 204, 204));
        pnlCards.setLayout(new java.awt.CardLayout());
        pnlCards.add(pnlDoanhThu, "card2");
        pnlCards.add(pnlHoaDon, "card3");
        pnlCards.add(pnlSanPham, "card4");

        add(pnlCards, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoanhThuMouseClicked
        // TODO add your handling code here:
        t.changePanel(pnlDoanhThu,pnlCards);
    }//GEN-LAST:event_btnDoanhThuMouseClicked

    private void btnSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSanPhamMouseClicked
        // TODO add your handling code here:
        t.changePanel(pnlSanPham,pnlCards);
        
    }//GEN-LAST:event_btnSanPhamMouseClicked

    private void btnHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoaDonMouseClicked
        // TODO add your handling code here:
        t.changePanel(pnlHoaDon,pnlCards);
        
    }//GEN-LAST:event_btnHoaDonMouseClicked

    private void btnSanPhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSanPhamMouseEntered
        // TODO add your handling code here:
        h.changeCursor(true, btnSanPham);
    }//GEN-LAST:event_btnSanPhamMouseEntered

    private void btnSanPhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSanPhamMouseExited
        // TODO add your handling code here:
        h.changeCursor(false, btnSanPham);

    }//GEN-LAST:event_btnSanPhamMouseExited

    private void btnHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoaDonMouseEntered
        // TODO add your handling code here:
        h.changeCursor(true, btnHoaDon);

    }//GEN-LAST:event_btnHoaDonMouseEntered

    private void btnHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoaDonMouseExited
        // TODO add your handling code here:
        h.changeCursor(false, btnHoaDon);

    }//GEN-LAST:event_btnHoaDonMouseExited

    private void btnDoanhThuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoanhThuMouseEntered
        // TODO add your handling code here:
        h.changeCursor(true, btnDoanhThu);

    }//GEN-LAST:event_btnDoanhThuMouseEntered

    private void btnDoanhThuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoanhThuMouseExited
        // TODO add your handling code here:
        h.changeCursor(false, btnDoanhThu);

    }//GEN-LAST:event_btnDoanhThuMouseExited

    private void init(){

    }
    TabbedPane t = new TabbedPane();
    Hover h = new Hover();

    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDoanhThu;
    private javax.swing.JLabel btnHoaDon;
    private javax.swing.JLabel btnSanPham;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlCards;
    private com.ul.DoanhThuPanel pnlDoanhThu;
    private com.ul.TKHoaDonPanel pnlHoaDon;
    private com.ul.TKSanPhamPanel pnlSanPham;
    // End of variables declaration//GEN-END:variables
}
